### ISSUE TITLE
while saving the model ValueError: tf.function-decorated function tried to create variables on non-first call

### ISSUE THREAD

**Issue by abdoelsayed2016** [Nikolai10/scrabble-gan#2] opened 2020-09-09 13:24 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution : Windows 10 x64 
- TensorFlow installed from : source
- TensorFlow version (use command below): 2.1 
- Python version:3.7
- Bazel version (if compiling from source):
- CUDA/cuDNN version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:26_Pacific_Standard_Time_2019
Cuda compilation tools, release 10.1, V10.1.105
- GPU model and memory:Tesla K20Xm

`
print('training...')
    for epoch_idx in range(epochs):
        start = time.time()

        for batch_idx in range(batch_per_epoch):
            image_batch, label_batch = next(dataset)
            #print(image_batch,label_batch)
            train_step(epoch_idx, batch_idx, batch_per_epoch, image_batch, label_batch, discriminator, recognizer,
                       composite_gan, generator_optimizer, discriminator_optimizer, recognizer_optimizer, batch_size,
                       latent_dim, loss_fn, disc_iters, random_words, bucket_size)
            
            generator.save(m_path + 'generator_'.format(batch_idx), save_format='tf')
        # Produce images for the GIF as we go
        generate_and_save_images(generator, epoch_idx + 1, seed_labels, gen_path, char_vector)

        # Save the model every 5 epochs
        if (epoch_idx + 1) % 5 == 0:
            checkpoint.save(file_prefix=checkpoint_prefix)

        print('Time for epoch {} is {} sec'.format(epoch_idx + 1, time.time() - start))
`

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-bc4217541666> in <module>()
      3 generator=train(train_dataset, generator, discriminator, recognizer, gan, checkpoint, checkpoint_prefix, generator_optimizer,
      4           discriminator_optimizer, recognizer_optimizer, [seed, labels], buf_size, batch_size, epochs, m_path,
----> 5           latent_dim, gen_path, loss_fn, disc_iters, random_words, bucket_size, char_vec)
      6 
      7 

<ipython-input-7-29447e8fa34b> in train(dataset, generator, discriminator, recognizer, composite_gan, checkpoint, checkpoint_prefix, generator_optimizer, discriminator_optimizer, recognizer_optimizer, seed_labels, buffer_size, batch_size, epochs, model_path, latent_dim, gen_path, loss_fn, disc_iters, random_words, bucket_size, char_vector)
     47                        latent_dim, loss_fn, disc_iters, random_words, bucket_size)
     48 
---> 49             generator.save(m_path + 'generator_'.format(batch_idx), save_format='tf')
     50         # Produce images for the GIF as we go
     51         generate_and_save_images(generator, epoch_idx + 1, seed_labels, gen_path, char_vector)

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1006     """
   1007     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
-> 1008                     signatures, options)
   1009 
   1010   def save_weights(self, filepath, overwrite=True, save_format=None):

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\saving\save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    113   else:
    114     saved_model_save.save(model, filepath, overwrite, include_optimizer,
--> 115                           signatures, options)
    116 
    117 

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save.py in save(model, filepath, overwrite, include_optimizer, signatures, options)
     76     # we use the default replica context here.
     77     with distribution_strategy_context._get_default_replica_context():  # pylint: disable=protected-access
---> 78       save_lib.save(model, filepath, signatures, options)
     79 
     80   if not include_optimizer:

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\saved_model\save.py in save(obj, export_dir, signatures, options)
    884   if signatures is None:
    885     signatures = signature_serialization.find_function_to_export(
--> 886         checkpoint_graph_view)
    887 
    888   signatures = signature_serialization.canonicalize_signatures(signatures)

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\saved_model\signature_serialization.py in find_function_to_export(saveable_view)
     72   # If the user did not specify signatures, check the root object for a function
     73   # that can be made into a signature.
---> 74   functions = saveable_view.list_functions(saveable_view.root)
     75   signature = functions.get(DEFAULT_SIGNATURE_ATTR, None)
     76   if signature is not None:

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\saved_model\save.py in list_functions(self, obj)
    140     if obj_functions is None:
    141       obj_functions = obj._list_functions_for_serialization(  # pylint: disable=protected-access
--> 142           self._serialization_cache)
    143       self._functions[obj] = obj_functions
    144     return obj_functions

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in _list_functions_for_serialization(self, serialization_cache)
   2418   def _list_functions_for_serialization(self, serialization_cache):
   2419     return (self._trackable_saved_model_saver
-> 2420             .list_functions_for_serialization(serialization_cache))
   2421 
   2422   def __getstate__(self):

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\base_serialization.py in list_functions_for_serialization(self, serialization_cache)
     89         `ConcreteFunction`.
     90     """
---> 91     fns = self.functions_to_serialize(serialization_cache)
     92 
     93     # The parent AutoTrackable class saves all user-defined tf.functions, and

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\layer_serialization.py in functions_to_serialize(self, serialization_cache)
     78   def functions_to_serialize(self, serialization_cache):
     79     return (self._get_serialized_attributes(
---> 80         serialization_cache).functions_to_serialize)
     81 
     82   def _get_serialized_attributes(self, serialization_cache):

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\layer_serialization.py in _get_serialized_attributes(self, serialization_cache)
     93 
     94     object_dict, function_dict = self._get_serialized_attributes_internal(
---> 95         serialization_cache)
     96 
     97     serialized_attr.set_and_validate_objects(object_dict)

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\model_serialization.py in _get_serialized_attributes_internal(self, serialization_cache)
     45     # cache (i.e. this is the root level object).
     46     if len(serialization_cache[constants.KERAS_CACHE_KEY]) == 1:
---> 47       default_signature = save_impl.default_save_signature(self.obj)
     48 
     49     # Other than the default signature function, all other attributes match with

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py in default_save_signature(layer)
    210   original_losses = _reset_layer_losses(layer)
    211   fn = saving_utils.trace_model_call(layer)
--> 212   fn.get_concrete_function()
    213   _restore_layer_losses(original_losses)
    214   return fn

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\def_function.py in get_concrete_function(self, *args, **kwargs)
    913       # In this case we have created variables on the first call, so we run the
    914       # defunned version which is guaranteed to never create variables.
--> 915       return self._stateless_fn.get_concrete_function(*args, **kwargs)
    916     elif self._stateful_fn is not None:
    917       # In this case we have not created variables on the first call. So we can

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\function.py in get_concrete_function(self, *args, **kwargs)
   2432       args, kwargs = None, None
   2433     with self._lock:
-> 2434       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2435       if self.input_signature:
   2436         args = self.input_signature

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   2701 
   2702       self._function_cache.missed.add(call_context_key)
-> 2703       graph_function = self._create_graph_function(args, kwargs)
   2704       self._function_cache.primary[cache_key] = graph_function
   2705       return graph_function, args, kwargs

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2591             arg_names=arg_names,
   2592             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2593             capture_by_value=self._capture_by_value),
   2594         self._function_attributes,
   2595         # Tell the ConcreteFunction to clean up its graph once it goes out of

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    976                                           converted_func)
    977 
--> 978       func_outputs = python_func(*func_args, **func_kwargs)
    979 
    980       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\def_function.py in wrapped_fn(*args, **kwds)
    437         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    438         # the function a weak reference to itself to avoid a reference cycle.
--> 439         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    440     weak_wrapped_fn = weakref.ref(wrapped_fn)
    441 

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\saving\saving_utils.py in _wrapped_model(*args)
    148     with base_layer_utils.call_context().enter(
    149         model, inputs=inputs, build_graph=False, training=False, saving=True):
--> 150       outputs_list = nest.flatten(model(inputs=inputs, training=False))
    151 
    152     try:

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    776                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    777                 else:
--> 778                   outputs = call_fn(cast_inputs, *args, **kwargs)
    779 
    780             except errors.OperatorNotAllowedInGraphError as e:

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\network.py in call(self, inputs, training, mask)
    715     return self._run_internal_graph(
    716         inputs, training=training, mask=mask,
--> 717         convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    718 
    719   def compute_output_shape(self, input_shape):

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\network.py in _run_internal_graph(self, inputs, training, mask, convert_kwargs_to_constants)
    889 
    890           # Compute outputs.
--> 891           output_tensors = layer(computed_tensors, **kwargs)
    892 
    893           # Update tensor_dict.

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    776                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    777                 else:
--> 778                   outputs = call_fn(cast_inputs, *args, **kwargs)
    779 
    780             except errors.OperatorNotAllowedInGraphError as e:

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\autograph\impl\api.py in wrapper(*args, **kwargs)
    290   def wrapper(*args, **kwargs):
    291     with ag_ctx.ControlStatusCtx(status=ag_ctx.Status.DISABLED):
--> 292       return func(*args, **kwargs)
    293 
    294   if inspect.isfunction(func) or inspect.ismethod(func):

C:\Users\a.abdallah\Desktop\GAN\russian-gan\src\bigacgan\arch_ops.py in call(self, input)
     38         theta = layers.Conv2D(filters=num_channels_attn, kernel_size=(1, 1), use_bias=False, strides=(1, 1),
     39                               padding='same', kernel_initializer=tf.initializers.orthogonal(),
---> 40                               kernel_regularizer=self.k_reg, name="conv2d_theta")(input)
     41         theta = self._spatial_flatten(theta)
     42 

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    746           # Build layer if applicable (if the `build` method has been
    747           # overridden).
--> 748           self._maybe_build(inputs)
    749           cast_inputs = self._maybe_cast_inputs(inputs)
    750 

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in _maybe_build(self, inputs)
   2114         # operations.
   2115         with tf_utils.maybe_init_scope(self):
-> 2116           self.build(input_shapes)
   2117       # We must set self.built since user defined build functions are not
   2118       # constrained to set self.built.

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\layers\convolutional.py in build(self, input_shape)
    156         constraint=self.kernel_constraint,
    157         trainable=True,
--> 158         dtype=self.dtype)
    159     if self.use_bias:
    160       self.bias = self.add_weight(

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint, partitioner, use_resource, synchronization, aggregation, **kwargs)
    444         synchronization=synchronization,
    445         aggregation=aggregation,
--> 446         caching_device=caching_device)
    447     backend.track_variable(variable)
    448 

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\training\tracking\base.py in _add_variable_with_custom_getter(self, name, shape, dtype, initializer, getter, overwrite, **kwargs_for_getter)
    742         dtype=dtype,
    743         initializer=initializer,
--> 744         **kwargs_for_getter)
    745 
    746     # If we set an initializer and the variable processed it, tracking will not

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\base_layer_utils.py in make_variable(name, shape, dtype, initializer, trainable, caching_device, validate_shape, constraint, use_resource, collections, synchronization, aggregation, partitioner)
    140       synchronization=synchronization,
    141       aggregation=aggregation,
--> 142       shape=variable_shape if variable_shape else None)
    143 
    144 

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\ops\variables.py in __call__(cls, *args, **kwargs)
    256   def __call__(cls, *args, **kwargs):
    257     if cls is VariableV1:
--> 258       return cls._variable_v1_call(*args, **kwargs)
    259     elif cls is Variable:
    260       return cls._variable_v2_call(*args, **kwargs)

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\ops\variables.py in _variable_v1_call(cls, initial_value, trainable, collections, validate_shape, caching_device, name, variable_def, dtype, expected_shape, import_scope, constraint, use_resource, synchronization, aggregation, shape)
    217         synchronization=synchronization,
    218         aggregation=aggregation,
--> 219         shape=shape)
    220 
    221   def _variable_v2_call(cls,

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\ops\variables.py in getter(**kwargs)
     63 
     64   def getter(**kwargs):
---> 65     return captured_getter(captured_previous, **kwargs)
     66 
     67   return getter

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\def_function.py in invalid_creator_scope(*unused_args, **unused_kwds)
    500       """Disables variable creation."""
    501       raise ValueError(
--> 502           "tf.function-decorated function tried to create "
    503           "variables on non-first call.")
    504 

ValueError: tf.function-decorated function tried to create variables on non-first call.
```

**Comment by abdoelsayed2016** [comment] 2020-09-09 13:24
i think because the generator not training

**Comment by Nikolai10** [comment] 2020-09-12 05:34
Duplicate of #1

**Closed by Nikolai10** 2020-09-12 05:34 UTC
